from selenium.webdriver.common.by import By


class Selector:
    ADMIN = (By.CSS_SELECTOR, "#globalLinks ul > li:nth-child(3) a")
    ACT = (By.CSS_SELECTOR, "#ajaxHeader .desktop-toolbar > ul > li:nth-child(5) .dropdown-menu")
    ADD_FAVORITES = (By.CSS_SELECTOR, "#pagecontent > .moduleTitle > .favorite")
    ASSIGNED_TO = (By.CSS_SELECTOR, "#assigned_user_name")
    ALL_CHECKBOX = (By.CSS_SELECTOR, "#MassUpdate > div.list-view-rounded-corners > table > tbody > tr")
    ADD_NEW_TASK = (By.CSS_SELECTOR, "#add_button")
    ACTION_EDIT = (By.CSS_SELECTOR, "#tab-actions ul > li:nth-child(1) > #edit_button")
    BUTTON_LOGIN = (By.CSS_SELECTOR, "#bigbutton")
    BUTTON_DELETED_TASK = (By.CSS_SELECTOR, "#actionLinkBottom ul > li:nth-child(3) a")
    BUTTON_DELETED = (By.CSS_SELECTOR, "#dashletPanel .oddListRowS1 .byLineBox > .byLineRight a")
    BUTTON_POST = (By.CSS_SELECTOR, ".dashletPanel > .bd .dashletNonTable tbody > tr td:nth-child(3) input")
    # для успешного прохождения теста CLICK_BUTTON_IMPORT_NOW = (By.CSS_SELECTOR, "#importnow")
    CLICK_BUTTON_IMPORT_NOW = (By.CSS_SELECTOR, "#importnow_1")
    CREATE_ADDRESS_CACHE = (By.CSS_SELECTOR, "#actionMenuSidebar > ul > li:nth-child(2) > a > div.actionmenulink")
    CREATE_PROJECT = (By.CSS_SELECTOR, "#actionMenuSidebar > ul > li:nth-child(2) > a > div.actionmenulink")
    CREATE_DOCUMENT = (By.CSS_SELECTOR, "#quickcreatetop > ul > li:nth-child(5) > a")
    CREATE_CALLS = (By.CSS_SELECTOR, "#toolbar > #quickcreatetop ul > li:nth-child(6) a")
    COLLABORATION = (By.CSS_SELECTOR, "#ajaxHeader .desktop-toolbar > ul > li:nth-child(6) #grouptab_4")
    COLLABORATION_PROJECT = (By.CSS_SELECTOR, "#moduleTab_9_Projects")
    CHECKBOX = (By.CSS_SELECTOR, ".oddListRowS1 > td  input[type='checkbox']")
    CREATE_TASK = (By.CSS_SELECTOR, "#toolbar > #quickcreatetop ul > li:nth-child(7) a")
    CHOICE_DATE = (By.CSS_SELECTOR, "#date_start_trigger_div_t_cell28")
    CLICK_SEARCH_BUTTON = (By.CSS_SELECTOR, "#ajaxHeader .desktop-bar > #toolbar #searchbutton")
    CLICK_BUTTON_LOUPE = (
        By.CSS_SELECTOR, "#ajaxHeader .desktop-bar > #toolbar #searchformdropdown > .input-group button")
    CREATE_NEW_USER = (By.CSS_SELECTOR, "#actionMenuSidebar ul > li:nth-child(2) a > .actionmenulink")
    CONFIRM_PASSWORD = (By.CSS_SELECTOR, "#confirm_pwd")
    DATE_START = (By.CSS_SELECTOR, "#estimated_start_date")
    DATE_END = (By.CSS_SELECTOR, "#estimated_end_date")
    DOWNLOAD_FILE_DOC = (By.CSS_SELECTOR, "#filename_file")
    DOC_NAME = (By.CSS_SELECTOR, "#document_name")
    DURATION_HOURS = (By.CSS_SELECTOR, "#duration_hours")
    DESCRIPTION = (By.CSS_SELECTOR, "#description")
    DELETE_TASK = (By.CSS_SELECTOR, "#delete_listview_bottom")
    H2 = (By.CSS_SELECTOR, "h2")
    INPUT_REQUEST = (By.CSS_SELECTOR, "#ajaxHeader .desktop-bar > #toolbar #searchformdropdown #query_string")
    IMPORT_CALL_BUTTON = (By.CSS_SELECTOR, "#actionMenuSidebar ul li:nth-child(4) a")
    LOGOUT = (By.CSS_SELECTOR, "#globalLinks ul > li:nth-child(6) a")
    LOGIN = (By.CSS_SELECTOR, "#user_name")
    LIST_FAVORITES = (By.CSS_SELECTOR, "#favoritesSidebar > ul > div > li > a > span")
    LAT = (By.CSS_SELECTOR, "#lat")
    LNG = (By.CSS_SELECTOR, "#lng")
    LAST_NAME = (By.CSS_SELECTOR, "#last_name")
    MENU_ALL = (By.CSS_SELECTOR, "#ajaxHeader .desktop-toolbar > ul > li:nth-child(7) #grouptab_5")
    MENU_ALL_MAPS_ADDR_CACHE = (
        By.CSS_SELECTOR, "#toolbar > ul > li.topnav.all > span.notCurrentTab > ul > li:nth-child(31) > a")
    MENU_ACTIV = (By.CSS_SELECTOR, "#ajaxHeader .desktop-toolbar > ul > li:nth-child(5) #grouptab_3")
    MENU_ACTIV_CALLS = (By.CSS_SELECTOR, "#ajaxHeader .desktop-toolbar > ul > li:nth-child(5) ul li:nth-child(3)")
    MENU_ACTIONS = (By.CSS_SELECTOR, "#content > #pagecontent .detail-view ul > #tab-actions")
    NEXT = (By.CSS_SELECTOR, "#gonext")
    NAME_SUBJECT = (By.CSS_SELECTOR, "#name")
    NO_DATA = (By.CSS_SELECTOR, "#dashletPanel .oddListRowS1 td  em")
    NEW_PASSWORD = (By.CSS_SELECTOR, "#new_password")
    OPEN_CALENDAR = (By.CSS_SELECTOR, "#date_start_trigger")
    PHOTO_FILE_DOWNLOAD = (By.CSS_SELECTOR, "#photo_file")
    PHOTO = (By.CSS_SELECTOR, "#photo > img")
    PASSWORD = (By.CSS_SELECTOR, "#username_password")
    PROFILE = (By.CSS_SELECTOR, "#globalLinks ul > li:first-child a")
    PASSWORD_TAB = (By.CSS_SELECTOR, "#tab2")
    RESULT_MESSAGE = (By.CSS_SELECTOR, "#pagecontent > div > div > div > span")
    REMOVE = (By.CSS_SELECTOR, "#remove_button")
    SEND_USER_NAME = (By.CSS_SELECTOR, "#user_name")
    SUBJECT = (By.CSS_SELECTOR, ".oddListRowS1 > td:nth-child(4) a")
    START = (By.CSS_SELECTOR, "#Start")
    SAVE_HEADER = (By.CSS_SELECTOR, "#SAVE_HEADER")
    SAVE = (By.CSS_SELECTOR, "#SAVE")
    SAVE_FOOTER = (By.CSS_SELECTOR, "#SAVE_FOOTER")
    SELECT_STATUS = (By.CSS_SELECTOR, "#status")
    SELECT_DURATION_MINUTES = (By.CSS_SELECTOR, "#duration_minutes")
    SEARCH_RESULTS = (By.CSS_SELECTOR, "#pagecontent table tr td a")
    TEXT_POST = (By.CSS_SELECTOR, "#text")
    TASK_NAME = (By.CSS_SELECTOR, "#task_name")
    TABLE_TASK = (
        By.CSS_SELECTOR, "#Task_table > tbody > tr.row_sortable.ui-sortable-handle > td:nth-child(2) > span > a")
    USER_FILE = (By.CSS_SELECTOR, "#userfile")
    USER = (By.CSS_SELECTOR, "#with-label")
    VIEW_TASK = (By.CSS_SELECTOR, "#actionMenuSidebar ul > li:nth-child(3) a > .actionmenulink")